cors:
  allowed-origin-patterns:
    - "http://*.${DOMAIN_NAME}"
    - "http://${DOMAIN_NAME}"

server:
  tomcat:
    basedir: "tomcat-logs"
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D microseconds)"

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        cache: DEBUG
      ehcache: DEBUG
      apache:
        coyote: WARN
        catalina:
          connector: DEBUG