spring:
  application:
    name: codogma-back
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            directory:
              root: ${user.home}/codogma/lucene/indexes
            type: lucene
            analysis:
              configurer: class:com.github.codogma.codogmaback.config.SearchAnalysisConfigurer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  mail:
    host: ${MAIL_SMTP_HOST}
    port: ${MAIL_SMTP_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      domain: ${DOMAIN_NAME}
      alg: HS512
      kid: ${KID}
      device-claim-name: deviceId
      device-salt: ${DEVICE_SALT}
      same-site: Lax
      issuer: codogma-service
      audience: codogma-back
      access-token-name: access_token
      refresh-token-name: refresh_token
      access-expiration: 60
      refresh-expiration: 604800
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: read_user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitLab
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: id
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      tti-minutes: 60
      max-heap-entries: 1000

server:
  servlet:
    context-path: /api
  port: 9000

cors:
  max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    caches:
      access: read_only
    metrics:
      access: read_only

user:
  avatar:
    upload-dir: ${user.home}/codogma/users/avatars

article:
  image:
    upload-dir: ${user.home}/codogma/articles/images

category:
  image:
    upload-dir: ${user.home}/codogma/categories/images

compilation:
  image:
    upload-dir: ${user.home}/codogma/compilations/images

search:
  results:
    limit: 1000
  mass:
    indexer:
      threads: 5

recommendation:
  limit: 5

opennlp-models:
  path:
    pos: opennlp-models/opennlp-ru-ud-gsd-pos-1.3-2.5.4.bin
    lemmas: opennlp-models/opennlp-ru-ud-gsd-lemmas-1.3-2.5.4.bin