package com.github.codogma.codogmaback.model;

public enum NotificationType {
  SYSTEM, ARTICLE_MODERATION, COMMENT_MODERATION, COMMENT_REPLIED, ARTICLE_COMMENTED, ARTICLE_PUBLISHED, ARTICLE_DRAFT, REMINDER
}
